- mutect_1.1.5/README.md
- mutect_1.1.5/container/Dockerfile
- mutect_1.1.5/example_inputs.yaml
- mutect_1.1.5/mutect_1.1.5.cwl
> add mutect 1.1.5 module

- abra2_2.19/abra2_2.19.cwl
- picard_add_or_replace_read_groups_1.96/picard_add_or_replace_read_groups_1.96.cwl
- picard_add_or_replace_read_groups_2.21.2/picard_add_or_replace_read_groups_2.21.2.cwl
- picard_fix_mate_information_1.96/picard_fix_mate_information_1.96.cwl
- picard_fix_mate_information_2.21.2/picard_fix_mate_information_2.21.2.cwl
✔️ Updated the TMP_DIR to be in the arguments section for Picard
> Adding TMP_DIR to arguments section

- picard_add_or_replace_read_groups_1.96/picard_add_or_replace_read_groups_1.96.cwl
- picard_fix_mate_information_1.96/picard_fix_mate_information_1.96.cwl
> Making temporary_directory as Directory instead of string

- vcf2maf_1.6.17/README.md
- vcf2maf_1.6.17/container/Dockerfile
- vcf2maf_1.6.17/example_inputs.yaml
- vcf2maf_1.6.17/vcf2maf_1.6.17.cwl
> Feature/vcf2maf 1.6.17

- bwa_mem_0.7.17/bwa_mem_0.7.17.cwl
- bwa_mem_0.7.17/container/Dockerfile
Is this a good name for the container `mskaccess/bwa_mem_0.7.17:0.1.0`?
> Ij/bwa v0.7.17

- picard_fix_mate_information_2.9.0/container/Dockerfile
- picard_fix_mate_information_2.9.0/picard_fix_mate_information_2.9.0.cwl
- picard_mark_duplicates_2.9.0/picard_mark_duplicates_2.8.1.cwl
I haven't built the containers and pushed them to docker hub yet, can someone confirm for me that `mskaccess/picard_2.9.0:0.1.0` is an appropriate tag to name them in docker hub?
> picard 2.9.0

- docs/SUMMARY.md
- fgbio_fastq_to_bam_1.2.0/README.md
- fgbio_fastq_to_bam_1.2.0/example_inputs.yaml
- fgbio_fastq_to_bam_1.2.0/fgbio_fastq_to_bam_1.2.0.cwl
> Adding workign version of fgbio fastqtobam

- docs/SUMMARY.md
- gatk_sam_to_fastq_4.1.8.0/README.md
- gatk_sam_to_fastq_4.1.8.0/example_inputs.yaml
- gatk_sam_to_fastq_4.1.8.0/gatk_sam_to_fastq_4.1.8.0.cwl
Tested successfully with a small dataset.
Closes #48
> Adding GATK-SamToFastq

- docs/SUMMARY.md
- gatk_merge_sam_files_4.1.8.0/README.md
- gatk_merge_sam_files_4.1.8.0/example_inputs.yaml
- gatk_merge_sam_files_4.1.8.0/gatk_merge_sam_files_4.1.8.0.cwl
Tested successfully with some example data using toil. Resolves #73
> Add GATK-MergeSamFiles

- docs/SUMMARY.md
- gatk_merge_bam_alignment_4.1.8.0/README.md
- gatk_merge_bam_alignment_4.1.8.0/example_inputs.yaml
- gatk_merge_bam_alignment_4.1.8.0/gatk_merge_bam_alignment_4.1.8.0.cwl
Tested successfully with some example data via toil. Resolves #72
> Adding MergeBamAlignment

- docs/SUMMARY.md
- picard_mark_duplicates_4.1.8.1/README.md
- picard_mark_duplicates_4.1.8.1/example_inputs.yaml
- picard_mark_duplicates_4.1.8.1/picard_mark_duplicates_4.1.8.1.cwl
> Added picard_mark_duplicates version 4.1.8.1

- docs/SUMMARY.md
- picard_fix_mate_information_4.1.8.1/README.md
- picard_fix_mate_information_4.1.8.1/example_inputs.yaml
- picard_fix_mate_information_4.1.8.1/picard_fix_mate_information_4.1.8.1.cwl
> Added picard_fix_mate_information version 4.1.8.1

- docs/SUMMARY.md
- picard_add_or_replace_read_groups_4.1.8.1/README.md
- picard_add_or_replace_read_groups_4.1.8.1/example_inputs.yaml
- picard_add_or_replace_read_groups_4.1.8.1/picard_add_or_replace_read_groups_4.1.8.1.cwl
> Added picard_add_or_replace_read_groups version 4.1.8.1

- docs/SUMMARY.md
- gatk_apply_bqsr_4.1.8.1/README.md
- gatk_apply_bqsr_4.1.8.1/example_inputs.yml
- gatk_apply_bqsr_4.1.8.1/gatk_apply_bqsr_4.1.8.1.cwl
- gatk_base_recalibrator_4.1.8.1/README.md
- gatk_base_recalibrator_4.1.8.1/example_inputs.yml
- gatk_base_recalibrator_4.1.8.1/gatk_base_recalibrator_4.1.8.1.cwl
> Adding GATK Base Recalibrator and GATK BQSR 4.1.8.1

- abra2_2.22/abra2_2.22.cwl
- picard_fix_mate_information_4.1.8.1/picard_fix_mate_information_4.1.8.1.cwl
I needed to make these changes before I was able to successfully test the indel realignment sub-workflow (here is the [PR](https://github.com/msk-access/cwl_subworkflows/pull/150)).
I am still a novice to to cwl/toil, so let me know if I misunderstood anything.
> Fixes for indel realignment workflow

- picard_add_or_replace_read_groups_4.1.8.1/picard_add_or_replace_read_groups_4.1.8.1.cwl
I could not test the alignment pipeline without this fix.
> fix create index param

- expression_tools/put_in_dir.cwl
thank you @ionox0 for the suggestions
> can handle list of files now

- docs/SUMMARY.md
- gatk_revert_sam/4.1.8.0/example_inputs.yaml
- gatk_revert_sam/4.1.8.0/gatk_revert_sam_4.1.8.0.cwl
- gatk_revert_sam/README.md
- I need to add this to the QC workflow to properly calculate mean target coverage in uncollapsed BAM.
- I tested is successfully on some example data.
> Add revert sam

- multiqc/1.10.1.7/multiqc.cwl
> set multiqc output directory name

- cci_utils/0.1.7/example_inputs.yaml
- cci_utils/0.1.7/general_stats_parse.cwl
A few fixes from cci_utils.cwl review: 
:heavy_check_mark: update output folder
:heavy_check_mark: making config file required
> updates to fix cci_utils

- vardictjava/v1.8.2/vardict_single_sample.cwl
@rhshah secondary file is changed from ^.fai to .fai
> fai change

- bcftools_1.15.1/bcftools_bgzip_1.15.1.cwl
- bcftools_1.15.1/bcftools_sort._1.15.1.cwl
- vardictjava/v1.8.2/var_to_vcf.cwl
@rhshah java script for output in the var2vcf file. Can you please review it?
> Var2vcf output

- biometrics_extract/0.2.13/biometrics_extract.cwl
- biometrics_extract/README.md
> Change biometrics extract

- vardictjava/v1.8.2/var_to_vcf.cwl
- vardictjava/v1.8.2/vardict_app.cwl
- vardictjava/v1.8.2/vardict_single_sample.cwl
@Ronak for your perusal. this is for fixing the post processing script with float and string values.
> Vardict af change

- snpsift_annotate_5.0/snpsift_annotate_5-0.cwl
@rhshah There was some newer code in this file which were causing the error. Had to remove them.
> removal of output_file_name

- docs/SUMMARY.md
- docs/oncokb_annotator/README.md
- docs/oncokb_annotator/oncokb_annotator_3.2.2.md
- oncokb_annotator_3.2.2/example_input.yml
- oncokb_annotator_3.2.2/oncokb_annotator_3-2-2.cwl
> Onco kb annotator

- oncokb_annotator_3.2.2/oncokb_annotator_3-2-2.cwl
- postprocessing_variant_calls/0.2.2/maf_annotated_by_bed/maf_annotated_by_bed.cwl
- snpsift_annotate_5.0/snpsift_annotate_5-0.cwl
- vcf2maf_1.6.21/vcf2maf_1.6.21.cwl
> Outputfile name change

- docs/SUMMARY.md
- docs/postprocessing_variant_calls/maf_annotated_by_bed_0.2.2.md
- docs/postprocessing_variant_calls/maf_annotated_by_tsv_0.2.3.md
- docs/postprocessing_variant_calls/maf_filter_cmoch_0.2.3.md
- docs/postprocessing_variant_calls/maf_tag_cmoch_0.2.3.md
- postprocessing_variant_calls/0.2.3/maf_annotated_by_bed/README.md
- postprocessing_variant_calls/0.2.3/maf_annotated_by_bed/maf_annotated_by_bed.cwl
- postprocessing_variant_calls/0.2.3/maf_annotated_by_tsv/README.md
- postprocessing_variant_calls/0.2.3/maf_annotated_by_tsv/maf_annotated_by_tsv.cwl
- postprocessing_variant_calls/0.2.3/maf_filter_cmoch/README.md
- postprocessing_variant_calls/0.2.3/maf_filter_cmoch/maf_filter_cmoch.cwl
- postprocessing_variant_calls/0.2.3/maf_tag_cmoch/README.md
- postprocessing_variant_calls/0.2.3/maf_tag_cmoch/maf_tag_cmoch.cwl
@rhshah Image and the readme are updated. please let me know if any other change is required.
> Image 0.2.3

- postprocessing_variant_calls/0.2.3/pv_vardict_case-control_filter/README.md
- postprocessing_variant_calls/0.2.3/pv_vardict_case-control_filter/example_input_case-control_filter.yml
- postprocessing_variant_calls/0.2.3/pv_vardict_case-control_filter/pv_vardict_case-control_filter.cwl
- postprocessing_variant_calls/0.2.3/pv_vardict_single_filter/README.md
- postprocessing_variant_calls/0.2.3/pv_vardict_single_filter/example_input_single_filter.yml
- postprocessing_variant_calls/0.2.3/pv_vardict_single_filter/pv_vardict_single_filter.cwl
@rhshah please review at your convenience.
> Pv sorting update
